application: corebackend
version: 1
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /debug.html
  static_files: debug.html
  upload: debug.html
  secure: always
- url: /handler.html
  script: corebackend.Main.app
  secure: always
  
libraries:
- name: PIL
  version: latest
- name: ssl
  version: latest